image: node:16-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}

stages:
- build
- production

build:
  stage: build
  tags:
    - docker
  script:
    - npm install


production:
  stage: production
  image: ruby:latest
  script:
    - apk update && apk add git curl
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=APPNAME_OF_Heroku App --api-key=$HEROKU_API_KEY # security add the heroku api to CI/CD setting
  only:
    refs:
    - main  #branch name to deploy on heroku
    variables:
      - $HEROKU_APP_NAME
      - $HEROKU_API_KEY
